[package]
name = "example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"
hf-hub = "0.4"
pgvector = { path = "../..", features = ["postgres"] }
postgres = "0.19"
serde_json = "1"
tokenizers = "0.21"
