[package]
name = "example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pgvector = { path = "../..", features = ["postgres"] }
postgres = "0.19"
serde_json = "1"
ureq = { version = "3", features = ["json"] }
